### PR TITLE
[ch46955] Dedicated Amazon Comprehend Medical plugin

### PR DESCRIPTION
**Pull request by alexcombessie**
Link to clubhouse story [ch46955](https://app.clubhouse.io/dataiku/story/46955/ux-enhancement-and-backend-refactoring)

### CODE REVIEW

**Comment by alexcombessie** [comment]
Hi @MayeulRousselet! Will you have some time to look at this PR this week? It's exactly similar to the Amazon Comprehend (no medical) one which has been merged. Thanks!

**Comment by alexcombessie** [comment]
👋 @MayeulRousselet

**Comment by alexcombessie** [comment]
TODO add logging if entities are filtered by the minimum_score parameter

**Review by MayeulRousselet — APPROVED** [review]
Ok for me, good work

**Pull request merged**
